# Generated by Django 4.2.29 on 2026-03-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('travel_type', models.CharField(max_length=20)),
                ('travel_id', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
